### ISSUE TITLE
Using Omise.js on hybrid mobile app

### ISSUE THREAD

**Issue by PanJ** [omise/omise.js#11]
I am having problem using Omise.js on Ionic mobile app. After digging in to the problem, I found that easyXDM cannot run on the local environment even if I loaded Omise.js through CDN.

Using Omise.js on Ionic/Cordova apps does not require easyXDM since there is no same-domain restriction. Would it be possible that you create another version of Omise.js just for hybrid mobile application?

Thanks!

**Comment by jonli29** [comment]
@PanJ and??? can you use this with ionic??

**Comment by robinclart** [comment]
@jonli29 You can use https://github.com/omise/omise-node for hybrid apps development. Omise.js is specifically designed for browser.

**Comment by trstowell** [comment]
@robinclart How do you expect we securely send card data to our node server?
