### ISSUE TITLE
Shows a warning when invoked from file:// or other unsupported URL schemes.

### ISSUE THREAD

**Issue by chakrit** [omise/omise.js#13]
Since some non-tech-savvy customers will try to integrate it and it'll fail with various confusing errors:
- Form gets submitted to a non-existent URL (because `Omise.createToken` throws and `return false;` wasn't called in a `submit` callback.)
- Garbled error messages gets printed out due to obfuscation (undefined variable `n`!??!?)

**Comment by sirn** [comment]
Or maybe support running from `file://`, i.e. fallback to XHR if XDM fails. I'm not sure if CORS and XHR stuff will work from a file though.

**Comment by robinclart** [comment]
If I remember correctly, framework like phonegap should just work with XHR. There's maybe a whitelisting to do in the config of the project but that should be all.
