### ISSUE TITLE
Extra 200kB from pay.js and font files

### ISSUE THREAD

**Issue by PanJ** [omise/omise.js#14]
I am optimizing my site speed and found out that `omise.js` creates an iframe with `pay.js` loaded and it loaded `Circular` font respectively.

Those files add roughly 200kB (gzipped) to the page load. I don't know in detail but I think they are unnecessary for the `omise.js` to run properly based on the fact that APIs of `omise.js` are just `setPublicKey` and `createToken`.

**Comment by robinclart** [comment]
Hey PanJ, we just switched to this new implementation today. Thanks for reporting this. We'll make sure to only load the iframe in the right condition.

**Comment by PanJ** [comment]
Thanks for instant response! Please keep me updated via this issue.

Kob Khun Krub!

**Comment by robinclart** [comment]
Sure thing.

**Comment by robinclart** [comment]
@PanJ We have updated `Omise.js` to only inject the IFRAME when the page will load our new payment frame. People using the original API should not see any extra assets loaded anymore. We're invalidating the cache right now, so it could take an hour before the script is updated.

**Comment by PanJ** [comment]
Thank you!
