### ISSUE TITLE
Omise.js Ionic App Support

### ISSUE THREAD

**Issue by yanisMeghzifene** [omise/omise.js#15]
Hi Omise Team,

First of all, many thanks for the great product you delivered.
I would like to use Omise.js in an Ionic app -- but as others have pointed out in previous issues (issue#11), it is not possible and as such Ionic developers are encourage to use omise-node. However, as card data can not touch the developer's server, omise-node's token creation must happen on the client side. Is that understanding correct - and if so, could you please help shed some light on whether this is the best practice? Any other workarounds / fixes since then?

Many thanks in advance

**Comment by turboza** [comment]
Hi @yanisMeghzifene, you are correct that you can use Omise-node to perform a tokenization which will send the card data to Omise server directly with this command.

```js
omise.tokens.create(cardData, (err, token) => { ... })
```

For the full example, you can take a look inside the webpack example here 
https://github.com/turboza/omise-tokenization-example

**Comment by yanisMeghzifene** [comment]
Hi @turboza 

Many thanks for the answer. I am aware that Omise-node can perform a tokenization, however I can't send card data to my server to perform the tokenization using Omise-node (I am not PCI-compliant). How then could I perform the tokenization on the client-side, using Ionic (Omise.js does not work on mobile)?

**Comment by turboza** [comment]
@yanisMeghzifene You can use Omise-node to perform tokenization in your Ionic app. 

These are what you can do...
✅ Tokenize card info on your client (web, mobile app) using `omise.js` or `Omise-node` (Card info will be sent to Omise Server directly without passing your server)
✅ Send token from client side to server side
✅ Have public key on client side
✅ Have secret key in server side
✅ Perform a charge in server side using received token

And what you must not do...
❌ Tokenize card info on your server (Card info will be passed to your server from client side)
❌ Perform a charge on client side
❌ Have secret key on client side

You could adapt this client side example to use in your Ionic.
https://github.com/turboza/omise-tokenization-example/blob/master/webpack-javascript/script.js

**Comment by yanisMeghzifene** [comment]
@turboza 
Many thanks for the help -- I tried the vanilla JS and webpack examples and it worked great.
