### ISSUE TITLE
Can't find variable: Omise

### ISSUE THREAD

**Issue by PanJ** [omise/omise.js#16]
The error `Can't find variable: Omise` happened in one of our users. I thought it was browser compatibility issue. The user-agent turned out to be `Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like Gecko) Version/10.0 Mobile/14D27 Safari/602.1`, which is quite up-to-date.

Looking from the error, it seems that somehow user cannot load the Omise.js library. The timestamp is `2017-02-04T08:44:34.583Z` and IP address is in Chiang Mai, Thailand. I am not sure if there's any outages during that period? If not, do you have any similar case in the past?

Thanks!

**Comment by danfowler** [comment]
Closing as this happened some time ago, and Omise.js is accessible here:

* https://cdn.omise.co/omise.js
* https://cdn2.omise.co/omise.js

Re-open if it happens again.
