### ISSUE TITLE
typo in API ref 

### ISSUE THREAD

**Issue by pongsakornsemsuwan** [omise/omise.js#17]
In API Ref of Omise.js [here](https://www.omise.co/omise-js-api#credit-card-form), around Credit card form customization example

Should not it be just 'key' and not 'publicKey' for both configure and configureButton example?

[Here](https://github.com/omise/omise.js/blob/master/src/omise/card/button.ts#L64) is a chunk of code that is referencing 'key' , I believe

**Comment by danfowler** [comment]
Thanks for raising this.  `publicKey` is the supported parameter.

Please see the updated docs here: https://www.omise.co/omise-js-api#parameters
