### ISSUE TITLE
[suggestion] on pre-built card form submission

### ISSUE THREAD

**Issue by pongsakornsemsuwan** [omise/omise.js#18]
I like pre-built credit card form. It looks nice. 

However, this [line ](https://github.com/omise/omise.js/blob/master/src/omise/card/button.ts#L141) uses `form.submit()` which will not invoke `submit eventListener` or `onSubmit`. 
With this, users are forced to do form submission unless they build their own form. (which I don't want to)

It is different from previous [card.js](https://github.com/omise/card.js) in that card.js use the approach of appending new button and use .click()  (this will invoke submit eventListener)

          var button = formObject.ownerDocument.createElement('input')
          button.style.display = 'none'
          button.type = 'submit'
          formObject.appendChild(button).click()
          formObject.removeChild(button)

I'm not sure if there is a reason behind this but just want to let you know.

**Comment by danfowler** [comment]
Hello @pongsakornsemsuwan, to get this behavior, while still benefiting from the pre-built credit card form, set `onCreateTokenSuccess` to a callback that does what you want.  The form will not automatically submit.

See https://www.omise.co/omise-js-api#using-javascript
