### ISSUE TITLE
CSP header without script-src 'unsafe-inline'

### ISSUE THREAD

**Issue by chainans** [omise/omise.js#20]
We recently implemented CSP header on our site and try to avoid using script-src 'unsafe-inline' but it stuck somewhere in Omise.js file. (Seem like having trouble somewhere in createFrame function in vendor/easyXDM.js)

We only use Omise.setPublicKey and Omise.createToken in our code. Without this CSP header, everything looks okay. Is there any recommended way to do this?

Thanks

EDIT: Note that, actually, createToken seems to work fine (I get the token back) but there is an error from browser's console like the following.

Refused to execute JavaScript URL because it violates the following Content Security Policy directive: "script-src 'self' https://cdn.omise.co". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.
k	@	omise.js:1
...

**Comment by danfowler** [comment]
Hi @chainans.  Given (a) you're using the current version of Omise.js and (b) you have omitted the `unsafe-inline` keyword in your CSP, when you restrict yourself to using `Omise.setPublicKey` and `Omise.createToken`, then the browser seems to no longer raise an error in the console.

Thanks for raising!
