### ISSUE TITLE
NPM

### ISSUE THREAD

**Issue by okayawright** [omise/omise.js#37]
Feature suggestion: build and publish a NPM out of your script as an alternative distribution method and avoid registering any global variable (i.e. Omise and OmiseCard)

Thank you.

**Comment by cyberhck** [comment]
yes, please give a npm module, this is stupid,

**Comment by chenka** [comment]
I agree with you that it should publish to NPM for use as ES modules.
For registering global variable, I think it still necessary when use it directly from CDN for integration to 3rd party website. So, it should built difference version. NPM version should not register global variable.

**Comment by cyberhck** [comment]
of course, NPM shouldn't register global variable, I have a proposal for a new codebase, which publishes to npm correctly and generates a UMD global using webpack, so they can still do CDN if they want to or, can use npm. I'm waiting for their response on #41 , if maintainers say they're interested, I'd be willing to help.

**Comment by chenka** [comment]
Actually, Omise.js and this repo designed to be loaded from CDN directly only. In case of you would like to use NPM for now I suggest to use [omise-node](https://github.com/omise/omise-node) or if you'd like to use pre-built payment form, please load via CDN.

**Comment by cyberhck** [comment]
unless I'm missing something, that library isn't for browser, it uses node's API and can't be used in browser.
