### ISSUE TITLE
this repo is stupid

### ISSUE THREAD

**Issue by cyberhck** [omise/omise.js#41]
vendor has js files with invalid javascript, the way code is written is shit as well, I'd rather not use this library than to rely on unreliable code like this.

I want to suggest a few things, please make code modular, config should be made better, right now it uses `process.env.NODE_ENV`, which is also stupid on it's own.

Please respond if you want to refactor this library to be at least a bit more reliable.

**Comment by davidsneighbour** [comment]
I don't think anyone would want to refactor anything into anything after this rant. It's neither an issue nor does the code not work on production sites. If you have requirements that invalidate this code then you might want to start looking into solutions.

**Comment by cyberhck** [comment]
well, technically garbage code also works on on production sites, I've personally worked on those kinds of projects. Looking at code of this project, I don't trust it, and it kinda sucks.

Let me tell you why I don't like this:
- `process.env.NODE_ENV` doesn't exist on browser unless you mock or use webpack define plugin (I'd rather pass a env mode myself to the client)
- doesn't publish to npm, gives 2 endpoints for 2 cdns, I want to build this myself, and publish to more than 20 edge location that I have access to.
- package.json means almost nothing, there's a name, isn't published to npm, version is 2.x.x but there are no other releases on github or anywhere else for that matter
- has invalid javascript files in vendor directory (this isn't much as we don't really use them)

And again my last point was a request to respond if we want to refactor so we can make it more maintainable.

**Comment by davidsneighbour** [comment]
Yeah well, isn't that a much nicer issue report than "this is stupid *stompwithmyfeet"?

**Comment by cyberhck** [comment]
if you're confident on this I can try to rewrite the entire thing with good release pipeline with same tests and transfer the repo to omise later, please let me know if interested.

**Comment by chenka** [comment]
Actually, Omise.js and this repo designed to be loaded from CDN directly only. In case of you would like to use NPM for now I suggest to use [omise-node](https://github.com/omise/omise-node) or if you'd like to use pre-built payment form, please load via CDN.

**Comment by cyberhck** [comment]
it only confirmed the state of this library, there's no room for improvement.
