### ISSUE TITLE
Enable gzip compression on cdn version of the file

### ISSUE THREAD

**Issue by PanJ** [omise/omise.js#5]
Hello,

I am wondering if you can enable gzip compression for the omise.js hosted on cdn?

Thanks

**Comment by robinclart** [comment]
Sure thing. Will do.

**Comment by PanJ** [comment]
Cool!

**Comment by fred** [comment]
Hi @PanJ 
For now we have add a version of our assets using Gzip compression, just add .gz at the end of the asset file.
For example: 
- https://cdn.omise.co/omise.min.js.gz
- https://cdn.omise.co/json2.js.gz

The documentation will be updated soon.
We might make all assets gz by default, but we will research more the impact of change.

**Comment by PanJ** [comment]
@fred I am so impressed by how fast you guys react to the issue. Thank you so much. Keep up good work!

**Comment by fred** [comment]
you're welcome!
