### ISSUE TITLE
Omise API backend missing response header essential for CORS

### ISSUE THREAD

**Issue by illuminist** [omise/omise.js#62]
### Background

I'm trying to eliminate easyXDM and using browser builtin fetch function. One problem I found is when I tried to use fetch on the API, browser will send preflight request with OPTIONS first to check if server will can accept cross domain request. This doesn't happen with curl command which I referenced from and it took me hours to recognize the issue.

### Issue

Because browser fetch is doing preflight request first, the server need to return some essential headers, so say:

1. `Access-Control-Allow-Origin: *` for allowing access from every domain, or only `https://*` in production
1. `Access-Control-Allow-Methods: GET, POST, PATCH, DELETE` for possible request methods
1. `Access-Control-Allow-Headers: Content-Type, Authorization` for essential headers to be included in the request

These are needed for browser fetch function to work properly without need of easyXDM.

**Comment by piairoj** [comment]
Access-Control-Allow-Origin: * for allowing access from every domain, or only https://* in production
Access-Control-Allow-Methods: GET, POST, PATCH, DELETE for possible request methods
Access-Control-Allow-Headers: Content-Type, Authorization for essential headers to be included in the request
These are needed for browser fetch function to work properly without need of easyXDM.

**Comment by danfowler** [comment]
Hi @illuminist @piairoj this CORS issue is now resolved.

We do, of course, strongly recommend merchants use [Omise.js](https://www.omise.co/omise-js) to create tokens on the user's browser.

Hope this helps.  Have a nice day!
