### ISSUE TITLE
do you support Prompt Pay?

### ISSUE THREAD

**Issue by saiqulhaq** [omise/omise.js#70]

**Comment by saiqulhaq** [comment]
we got Service Not Found error 
![messageImage_1586247971262](https://user-images.githubusercontent.com/1275215/78652709-47c61400-78ec-11ea-9269-856f1ee033b9.jpg)

should we generate new key for staging?
we already got permission to use Prompt Pay feature btw

**Comment by danfowler** [comment]
@saiqulhaq you can create a new PromptPay source using Omise.js this way:

https://www.omise.co/promptpay#creating-a-source

But it looks like your API version might be lower than < `2017-11-02` which is the minimum API version supported for creating sources.

**Comment by saiqulhaq** [comment]
ok got it
I have to use custom header
