### ISSUE TITLE
Why this library is not on npm?

### ISSUE THREAD

**Issue by lnmunhoz** [omise/omise.js#74]
What is stopping you guys to do this? I am happy to help.

**Comment by danfowler** [comment]
Hi @lnmunhoz sorry for the inconvenience.  To help our merchants maintain PCI compliance, [Omise.js](https://www.omise.co/omise-js) is designed to be loaded directly from our CDN to the user's browser.  

See https://github.com/omise/omise.js/issues/37#issuecomment-517156238

**Comment by lnmunhoz** [comment]
If stripe is in npm why you can't be? That's not an excuse 😅

**Comment by MXfive** [comment]
Hi @lnmunhoz you can see the big warning Stripe put at the top of [their NPM page](https://www.npmjs.com/package/@stripe/stripe-js) telling you not to host it yourself and to instead load it from their CDN for PCI compliance.  What problem are would hosting this library on NPM solve for you?

**Comment by lnmunhoz** [comment]
Ok, I am stupid. Cheers guys! 👍 😅

**Comment by rayriffy** [comment]
At least can you provide TypeScript definition file for us to add it our shims package?
