### ISSUE TITLE
do you have any consent about CC data harvesting?

### ISSUE THREAD

**Issue by saiqulhaq** [omise/omise.js#77]
I just read this [article](https://medium.com/hackernoon/im-harvesting-credit-card-numbers-and-passwords-from-your-site-here-s-how-9a8cb347c5b5), I know that it's small possibility to be happen, but what if there is malicious Chrome extension or any JS script that collecting our customer CC data?

**Comment by Mazon** [comment]
Thank you for the question saiqulhaq. You are correct, it is very important to stay updated and try to make sure any security related issues do not happen. We at Omise takes this very serious and try our best to always improve.  We have a shared responsibility with our merchants to make sure our systems are secure. You can read more here https://www.omise.co/security-best-practices about some best practises that will help you mitigate some of your worries. 

Thanks again and if you have more questions, you can always reach out to support@omise.co or security@omise.co and we can try to help you further.

best regards
