### ISSUE TITLE
I can't use promptpay

### ISSUE THREAD

**Issue by minnyww** [omise/omise.js#91]
I create a checkout button with following code but show error is Payment method `promptpay` not found

I use React and omise cdn

```
OmiseCard.open({
         amount: "999900",
         currency: "THB",
         defaultPaymentMethod: "promptpay",
         onCreateTokenSuccess: async (nonce) => {
            console.log("nonce : ", nonce);
           
         },)
```

**Comment by danfowler** [comment]
@minnyww hi, unfortunately, the built-in form for Omise.js doesn't yet support PromptPay: https://www.omise.co/omise-js#supported-payment-methods-for-pre-built-form

However, you should still be able to create your own form which uses Omise.js to create a PromptPay source: https://www.omise.co/promptpay#creating-a-source

**Comment by hamzabinamin** [comment]
@danfowler How do I show the QR code? I was under the impression when I will create the source it will generate the QR code automatically.

**Comment by danfowler** [comment]
@hamzabinamin the QR code is only generated once the charge is created
