### ISSUE TITLE
PromptPay: Not receiving charge.complete event in test mode

### ISSUE THREAD

**Issue by hamzabinamin** [omise/omise.js#93]
Hi, when I scan the QR code in test mode, I don't see the charge.complete event in the event tab, only charge.create is created.

**Comment by danfowler** [comment]
Hi @hamzabinamin, to simulate the completion of a charge in test mode go to the charge in your dashboard and mark the charge as paid. This should send the `charge.complete` event.

![Screen Shot 2021-03-22 at 9 21 45 AM](https://user-images.githubusercontent.com/772616/111932464-0e33ec00-8af0-11eb-90f9-c51f374fbad4.png)
